### ISSUE TITLE
Images & text content do not match

### ISSUE THREAD

**Issue by LNKeat** [learn-co-curriculum/phase-3-ruby-remote-data-practice-scraping#1]
### Canvas Link

https://learning.flatironschool.com/courses/4323/assignments/127757?module_item_id=264275

### Concern

Both the images used for this lesson have different css selectors than the text & code that is used as an example below the images.   

### Additional Context

<img width="676" alt="Screen Shot 2022-02-01 at 5 27 08 PM" src="https://user-images.githubusercontent.com/81266679/152073756-1a2ce8e7-55df-4bde-a198-666ad8d36ee0.png">

### Suggested Changes

Updating the image or text & following code would make this less confusing.  Updating both to match the current website would be even more helpful.

**Comment by graciemcguire** [comment]
Hi @LNKeat,

Thank you for your feedback! We'll fix these images and tags in the next release of this lesson.

As always, thanks for contributing! 💙
